config/routes.rb
# frozen_string_literal: true

Deposit::Engine.routes.draw do
  root to: 'collection#index'

  resources :collection, only: [:index]

  scope '/collection' do
    match '/record' => 'collection#record_payments', :via => :post, :as => 'do_record_payments'
    match '/account_invoices' => 'collection#account_invoices', :via => :get, :as => 'account_invoices'
  end
end

app/controllers/deposit/collection_controller.rb
# frozen_string_literal: true

require 'deposit/client'

module Deposit
  class CollectionController < EngineController
    def index
      @account_id = params[:account_id]
      @currency = params[:currency] || 'USD'
    end

    def record_payments
      cached_options_for_klient = options_for_klient

      payments = {}
      params.each do |k, amount|
        next unless k.start_with?('payment_amount_')

        _, invoice_nb = k.split('payment_amount_')
        payments[invoice_nb] = amount
      end

      begin
        Killbill::Deposit::DepositClient.record_payments(params[:account_id],
                                                         params[:effective_date],
                                                         params[:payment_reference_number],
                                                         params[:deposit_type],
                                                         payments,
                                                         cached_options_for_klient[:username],
                                                         params[:reason],
                                                         params[:comment],
                                                         cached_options_for_klient)

        flash[:notice] = 'Deposit successfully collected'
        redirect_to kaui_engine.account_path(params[:account_id])
      rescue StandardError => e
        flash.now[:error] = case e
                            when ::KillBillClient::API::NotFound
                              'Unable to record payment: invoice not found'
                            when ::KillBillClient::API::BadRequest
                              'Unable to record payment: deposit type, reference date, and reference number must be specified'
                            when ::KillBillClient::API::UnprocessableEntity
                              'Unable to record payment: amount too small or payment in UNKNOWN state'
                            else
                              "Internal error: #{as_string(e)}"
                            end

        @account_id = params[:account_id]
        @currency = params[:currency] || 'USD'

        render :index
      end
    end

    def account_invoices
      cached_options_for_klient = options_for_klient

      searcher = lambda do |search_key, _offset, _limit|
        account = begin
          KillBillClient::Model::Account.find_by_id(search_key, false, false,
                                                    cached_options_for_klient)
        rescue StandardError
          nil
        end
        if account.nil?
          []
        else
          account.invoices(cached_options_for_klient)
        end
      end

      data_extractor = lambda do |invoice, column|
        [
          invoice.invoice_number.to_i,
          invoice.invoice_date,
          invoice.amount,
          invoice.balance,
          nil
        ][column]
      end

      formatter = lambda do |invoice|
        [
          invoice.invoice_number,
          invoice.invoice_date,
          view_context.humanized_money_with_symbol(Money.from_amount(invoice.amount.to_f, invoice.currency)),
          view_context.humanized_money_with_symbol(Money.from_amount(invoice.balance.to_f, invoice.currency)),
          nil
        ]
      end

      begin
        search_key = (params[:search] || {})[:value].presence
        offset = (params[:start] || 0).to_i
        limit = (params[:length] || 50).to_i
        pages = searcher.call(search_key, offset, limit)
      rescue StandardError => e
        error = e.to_s
      end

      json = {
        draw: (params[:draw] || 0).to_i,
        # We need to fill-in a number to make DataTables happy
        recordsTotal: pages.nil? ? 0 : limit,
        recordsFiltered: pages.nil? ? 0 : limit,
        data: []
      }
      json[:error] = error unless error.nil?

      pages ||= []

      # Until we support server-side sorting
      ordering = ((params[:order] || {})[:'0'] || {})
      ordering_column = (ordering[:column] || 0).to_i
      ordering_dir = ordering[:dir] || 'asc'
      unless search_key.nil?
        pages.sort! do |a, b|
          a = data_extractor.call(a, ordering_column)
          b = data_extractor.call(b, ordering_column)
          sort = a <=> b
          sort.nil? ? -1 : sort
        end
      end
      pages.reverse! if (ordering_dir == 'desc' && limit >= 0) || (ordering_dir == 'asc' && limit.negative?)

      pages.each { |page| json[:data] << formatter.call(page) }

      respond_to do |format|
        format.json { render json: json }
      end
    end

    private

    def options_for_klient
      user = current_tenant_user
      {
        username: user[:username],
        password: user[:password],
        session_id: user[:session_id],
        api_key: user[:api_key],
        api_secret: user[:api_secret],
        # Pass the X-Request-Id seen by Rails to Kill Bill
        # Note that this means that subsequent requests issued by a single action will share the same X-Request-Id in Kill Bill
        request_id: request.request_id
      }
    end
  end
end

app/controllers/deposit/engine_controller.rb
# frozen_string_literal: true

module Deposit
  class EngineController < ApplicationController
    layout :get_layout

    # Used to format flash error messages
    def as_string(e)
      if e.is_a?(KillBillClient::API::ResponseError)
        "Error #{e.response.code}: #{as_string_from_response(e.response.body)}"
      else
        log_rescue_error(e)
        e.message
      end
    end

    def log_rescue_error(error)
      Rails.logger.warn "#{error.class} #{error.to_s}. #{error.backtrace.join("\n")}"
    end

    def get_layout
      layout ||= Deposit.config[:layout]
    end

    def current_tenant_user
      # If the rails application on which that engine is mounted defines such method (Devise), we extract the current user,
      # if not we default to nil, and serve our static mock configuration
      user = current_user if respond_to?(:current_user)
      Deposit.current_tenant_user.call(session, user)
    end
  end
end

app/helpers/deposit/application_helper.rb
# frozen_string_literal: true

module Deposit
  module ApplicationHelper
  end
end

app/views/deposit/collection/_invoices_table.html.erb
<div class="search">

  <div class="column-block">

    <h1>Invoices</h1>

    <table id="invoices-table" class="table table-condensed mobile-data">
      <thead>
      <tr>
        <th>Number</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Balance</th>
        <th>Payment</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td colspan="1" class="dataTables_empty">Loading data from server</td>
      </tr>
      </tbody>
    </table>

    <div id="deposit_amount_mismatch" class="text-danger">
      Warning! Total amount doesn't match deposit.
    </div>
  </div>

</div>

<%= javascript_tag do %>
$(document).ready(function() {
  var table = $('#invoices-table').DataTable({
    "dom": "t",
    "paging": false,
    "ajax": "<%= account_invoices_path :format => :json %>",
    "processing": true,
    "serverSide": true,
    "search": {"search": $('#account_id').val()},
    "columnDefs": [
        {
          "targets": [ 4 ],
          "orderable": false
        }
      ],
    createdRow: function(row, data, dataIndex) {
      var disabled = data[3].replace(/\D/g, '') == 0 ? ' disabled' : '';
      $('td', row).eq(4).html('<input class="payment_amount_invoice" type="number" name="payment_amount_' + data[0] + '" id="payment_amount_' + dataIndex + '" value="0" step="any" class="form-control"' + disabled + '>')
    },
    drawCallback: function() {
      $('input').change(function() {
        var table = $('#invoices-table').DataTable();
        var total = 0;
        table.rows().every(function (rowIdx, tableLoop, rowLoop) {
          var d = this.data();
          total += parseFloat($('#payment_amount_' + rowIdx).val(), 10);
        });
        if (total != parseFloat($('#payment_amount').val(), 10)) {
          $('#deposit_amount_mismatch').css('visibility', 'visible');
          $('#submit-btn').prop('disabled', true);
        } else {
          $('#deposit_amount_mismatch').css('visibility', 'hidden');
          $('#submit-btn').prop('disabled', false);
        }
      });
    }
  });
});
<% end %>

app/views/deposit/collection/_payment_form.html.erb
<%= form_tag do_record_payments_path, :class => 'form-horizontal' do %>
  <div class="form-group">
    <%= label_tag :account_id, 'Account ID', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= text_field_tag :account_id, @account_id, :class => 'form-control', :readonly => !@account_id.nil?, :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :payment_amount, 'Amount Received', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= number_field_tag :payment_amount, nil, :step => :any, :id => 'payment_amount', :class => 'form-control', :required => true %>
      <p class="help-block">Currency: <%= @currency %></p>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :effective_date, 'Payment Date', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= text_field_tag :effective_date, Date.parse(Time.now.to_s).to_s, :class => 'form-control date-picker', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :payment_reference_number, 'Payment Ref. #', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= text_field_tag :payment_reference_number, nil, :class => 'form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :deposit_type, 'Payment Mode', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= select_tag :deposit_type, options_for_select(Deposit.deposit_types), :class => 'form-control' %>
    </div>
  </div>

  <div id="invoices">
    <% unless @account_id.nil? %>
      <%= render(:partial => 'invoices_table') %>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag 'Save', :id => 'submit-btn', :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function() {
    $('#account_id').change(function() {
      $("#invoices").html("<%= j render(:partial => 'invoices_table') %>");
    });
  });
<% end %>

app/views/deposit/collection/index.html.erb
<div class="register">
  <div class="col-md-10 col-md-offset-1">

    <div class="column-block">
      <h1>Record Payment</h1>
      <%= render 'payment_form' %>
    </div>

  </div>
</div>

app/views/deposit/layouts/deposit_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deposit</title>
  <%= yield :scripts %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<div class="container-fluid">
  <%- # :alert used by devise -%>
  <% [:error, :alert].each do |key| %>
      <% if flash[key] %>
          <div class="row">
            <div class="col-md-10 col-md-offset-2">
              <div class="alert alert-error"><%= flash[key] %></div>
            </div>
          </div>
      <% end %>
  <% end %>
  <% if flash[:notice] %>
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          <div class="alert alert-info"><%= flash[:notice] %></div>
        </div>
      </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>